// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that answers questions about a specific document.
 *
 * - askQuestionAboutDocument - A function that handles the question answering process.
 * - AskQuestionAboutDocumentInput - The input type for the askQuestionAboutDocument function.
 * - AskQuestionAboutDocumentOutput - The return type for the askQuestionAboutDocument function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AskQuestionAboutDocumentInputSchema = z.object({
  documentContent: z.string().describe('The content of the document.'),
  question: z.string().describe('The question to ask about the document.'),
});
export type AskQuestionAboutDocumentInput = z.infer<
  typeof AskQuestionAboutDocumentInputSchema
>;

const AskQuestionAboutDocumentOutputSchema = z.object({
  answer: z.string().describe('The AI-generated answer to the question.'),
  sources: z
    .array(z.string())
    .describe(
      'References to the source document that support the answer.  Each element should be a specific sentence or paragraph from the documentContent.'
    ),
});
export type AskQuestionAboutDocumentOutput = z.infer<
  typeof AskQuestionAboutDocumentOutputSchema
>;

export async function askQuestionAboutDocument(
  input: AskQuestionAboutDocumentInput
): Promise<AskQuestionAboutDocumentOutput> {
  return askQuestionAboutDocumentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askQuestionAboutDocumentPrompt',
  input: {schema: AskQuestionAboutDocumentInputSchema},
  output: {schema: AskQuestionAboutDocumentOutputSchema},
  prompt: `You are an AI assistant that answers questions about a document.

  You are given the content of the document and a question.
  Your task is to answer the question based on the information in the document.
  If the document does not contain the answer, respond that you cannot answer the question.
  Include references to the source document that support the answer.  Each element should be a specific sentence or paragraph from the documentContent.

  Document Content: {{{documentContent}}}

  Question: {{{question}}}

  Answer:
  `, // add sources here
});

const askQuestionAboutDocumentFlow = ai.defineFlow(
  {
    name: 'askQuestionAboutDocumentFlow',
    inputSchema: AskQuestionAboutDocumentInputSchema,
    outputSchema: AskQuestionAboutDocumentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
